In [1]:
import numpy as np

def generate_feature_matrix(M, N):
    return np.random.rand(M, N)

def compute_covariance_matrix(feature_matrix):
    return np.cov(feature_matrix)

def compute_correlation_matrix(covariance_matrix):

    std_dev = np.sqrt(np.diag(covariance_matrix))
    correlation_matrix = covariance_matrix / np.outer(std_dev, std_dev)
    np.fill_diagonal(correlation_matrix, 1)
    return correlation_matrix

# Example usage
M = 5  # Number of features
N = 10  # Number of samples

feature_matrix = generate_feature_matrix(M, N)

cov_matrix = compute_covariance_matrix(feature_matrix)

corr_matrix = compute_correlation_matrix(cov_matrix)


print("Feature Matrix (MxN):\n", feature_matrix)
print("\nCovariance Matrix (MxM):\n", cov_matrix)
print("\nCorrelation Matrix (MxM):\n", corr_matrix)


Feature Matrix (MxN):
 [[0.97817753 0.49009388 0.93214415 0.84513248 0.55299694 0.68207088
  0.48544455 0.10100476 0.65971707 0.51421371]
 [0.40562402 0.3594495  0.46569182 0.80472503 0.10489484 0.97176288
  0.26115687 0.80430917 0.42443916 0.85327006]
 [0.26770648 0.44942865 0.22415949 0.58066906 0.72268463 0.05598473
  0.31476124 0.03886854 0.19693251 0.03194323]
 [0.64286537 0.50816666 0.99694289 0.59680269 0.01667485 0.05413015
  0.49969341 0.97750649 0.40885093 0.88839354]
 [0.25814883 0.61215818 0.13111194 0.42167891 0.1904364  0.87887533
  0.43315575 0.1835827  0.29267908 0.90770827]]

Covariance Matrix (MxM):
 [[ 0.06685432 -0.00777009  0.01370563 -0.00701976 -0.00722621]
 [-0.00777009  0.08453237 -0.0418362   0.02678335  0.04530128]
 [ 0.01370563 -0.0418362   0.05506929 -0.03576951 -0.02300943]
 [-0.00701976  0.02678335 -0.03576951  0.11795115 -0.01965851]
 [-0.00722621  0.04530128 -0.02300943 -0.01965851  0.07986468]]

Correlation Matrix (MxM):
 [[ 1.         -0.10335931  0.2