In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
dataset = pd.read_csv('ToyotaCorolla.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values
dataset

Id                                              Model  Price  \
0        1      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500   
1        2      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750   
2        3     ?TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950   
3        4      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950   
4        5        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750   
...    ...                                                ...    ...   
1431  1438         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500   
1432  1439  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845   
1433  1440  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500   
1434  1441  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250   
1435  1442        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950   

      Age_08_04  Mfg_Month  Mfg_Year     KM Fuel_Type   HP  Met_Color  ...  \
0            23         10      2002  46986    Diesel   90          1  ...   
1            23         10      2002  72937    Diesel   90          1  ...   
2            24          9      2002  41711    Diesel   90          1  ...   
3            26          7      2002  48000    Diesel   90          0  ...   
4            30          3      2002  38500    Diesel   90          0  ...   
...         ...        ...       ...    ...       ...  ...        ...  ...   
1431         69         12      1998  20544    Petrol   86          1  ...   
1432         72          9      1998  19000    Petrol   86          0  ...   
1433         71         10      1998  17016    Petrol   86          0  ...   
1434         70         11      1998  16916    Petrol   86          1  ...   
1435         76          5      1998      1    Petrol  110          0  ...   

      Central_Lock  Powered_Windows  Power_Steering  Radio  Mistlamps  \
0                1                1               1      0          0   
1                1                0               1      0          0   
2                0                0               1      0          0   
3                0                0               1      0          0   
4                1                1               1      0          1   
...            ...              ...             ...    ...        ...   
1431             1                1               1      0          1   
1432             0                0               1      0          0   
1433             0                0               1      0          0   
1434             0                0               0      0          0   
1435             0                0               1      0          0   

      Sport_Model  Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar  
0               0                 1             0               0        0  
1               0                 1             0               0        0  
2               0                 1             0               0        0  
3               0                 1             0               0        0  
4               0                 1             0               0        0  
...           ...               ...           ...             ...      ...  
1431            1                 1             0               0        0  
1432            1                 1             0               0        0  
1433            0                 1             0               0        0  
1434            0                 1             0               0        0  
1435            0                 0             0               0        0  

[1436 rows x 37 columns]

In [30]:
df = dataset[["Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight"]]
df

Price  Age_08_04     KM   HP    cc  Doors  Gears  Quarterly_Tax  Weight
0     13500         23  46986   90  2000      3      5            210    1165
1     13750         23  72937   90  2000      3      5            210    1165
2     13950         24  41711   90  2000      3      5            210    1165
3     14950         26  48000   90  2000      3      5            210    1165
4     13750         30  38500   90  2000      3      5            210    1170
...     ...        ...    ...  ...   ...    ...    ...            ...     ...
1431   7500         69  20544   86  1300      3      5             69    1025
1432  10845         72  19000   86  1300      3      5             69    1015
1433   8500         71  17016   86  1300      3      5             69    1015
1434   7250         70  16916   86  1300      3      5             69    1015
1435   6950         76      1  110  1600      5      5             19    1114

[1436 rows x 9 columns]

In [31]:
x = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [33]:
y_test

array([ 7950, 10950, 14950,  7500,  9900,  8900,  6950, 15750, 11950,
        9930,  8500, 10450, 11895,  9950,  6450, 15500, 11950,  6900,
       10950,  9750,  7350,  8950, 13750, 14950, 19950,  9450, 11500,
        8500,  9450,  8800, 11450, 10500, 13750,  8250, 10950, 11950,
        8950, 12900,  9500,  9950,  8950,  9500,  9950, 15500, 10950,
        7500,  9450,  9500, 10845,  8500, 19750,  8950,  7250,  6750,
       10950, 19950, 11000,  8950, 17795, 10500,  5740,  7750, 10950,
       10500, 12500, 12900,  8450,  7950, 19450, 11450,  9500,  4450,
       11690,  7900, 14750, 14990,  9950,  7450,  6950,  8250,  6750,
        6900,  5950, 12750, 11950, 10750,  8950, 11950,  8250,  7450,
        6950, 10750, 17450,  9940,  7950, 12250, 12950, 10950, 12450,
        6900,  8500, 10750,  9700,  9250,  7900, 19000, 18450,  8500,
       13250, 10400, 12500,  9200,  8500,  8250, 13750,  8950,  7950,
       10950,  9900,  7750, 20500,  9950, 13995, 10250,  7950, 23950,
        7950, 11500,

In [34]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
regressor.coef_

array([-1.21138340e+02, -1.84009991e-02,  3.32294159e+01, -2.00293743e+00,
       -2.81967458e+01,  6.09551830e+02,  7.27983837e+00,  2.04162532e+01])

In [35]:
y_pred = regressor.predict(x_test)
y_bar = y_test.mean()
y_bar

10749.149305555555

In [39]:
SSE = sum((y_test-y_pred)**2)
SSR = sum((y_pred - y_bar)**2)
SST = sum((y_test-y_bar)**2)

In [41]:
R2 = 1-(SSE/SST)
print("Value of R2 is: ", R2)
mse = SSE/len(y_test)
y_test = np.array(y_test)
accuracy = 1 -(mse/y_test.var())
print("Value of accuracy is: ", accuracy)

Value of R2 is:  0.5995582859225215
Value of accuracy is:  0.5995582859225219


In [12]:
#standadization

In [13]:
columns_ls = df.columns[1:-1]
columns_ls


Index(['Age_08_04', 'KM', 'HP', 'cc', 'Doors', 'Gears', 'Quarterly_Tax'], dtype='object')

In [42]:
for column in columns_ls:
  mn = df[column].min()
  mx = df[column].max()
  df[column] = (dataset[column] - mn)/(mx - mn)

X = np.array(df.iloc[:, 1:].values)
y = np.array(df.iloc[:, 0].values)


<ipython-input-42-620541410416>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = (dataset[column] - mn)/(mx - mn)
<ipython-input-42-620541410416>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = (dataset[column] - mn)/(mx - mn)
<ipython-input-42-620541410416>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-doc

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
X_train

array([[8.35443038e-01, 7.19476212e-01, 2.43902439e-02, ...,
        6.66666667e-01, 6.28787879e-01, 1.10000000e+03],
       [6.32911392e-01, 2.19782797e-01, 3.33333333e-01, ...,
        6.66666667e-01, 2.50000000e-01, 1.08000000e+03],
       [7.46835443e-01, 2.55046317e-01, 1.38211382e-01, ...,
        6.66666667e-01, 1.89393939e-01, 1.01500000e+03],
       ...,
       [8.73417722e-01, 3.53347133e-01, 2.43902439e-02, ...,
        6.66666667e-01, 6.28787879e-01, 1.13500000e+03],
       [6.20253165e-01, 1.63395734e-01, 3.33333333e-01, ...,
        6.66666667e-01, 2.50000000e-01, 1.08000000e+03],
       [8.48101266e-01, 4.15639571e-01, 3.33333333e-01, ...,
        6.66666667e-01, 2.50000000e-01, 1.07500000e+03]])

In [17]:
y_pred = regressor.predict(X_test)

In [18]:
y_bar = y_test.mean()
SST = sum((y_test- y_bar)**2)
SSE = sum((y_test-y_pred)**2)
SSR = sum((y_pred - y_bar)**2)

In [24]:
r2 = 1 - (SSE/SST)

In [25]:
mse = SSE/len(y_test)
y_test = np.array(y_test)
accuracy = 1 -(mse/y_test.var())

In [26]:
print("value R-Squared error after standadization is: ",r2)
print("value accuracy after standadization is: ",accuracy)

value R-Squared error after standadization is:  0.5995582859225036
value accuracy after standadization is:  0.5995582859225042
